### ISSUE TITLE
Warning "Actual arrival ... earlier ..." not translated

### ISSUE THREAD

**Issue by syllant** [furkot/locale#10]
The warning "Actual arrival on MM/DD/YYYY at is earlier than planned" is not translated on French version.

Also, it seems like time is missing in sentence (after "at").

**Comment by melitele** [comment]
We need to annotate warnings and generate a new .pot file

**Comment by melitele** [comment]
All warnings have been automatically translated. I'll be most grateful if you can find time to review the updated French translation on the master branch.

**Comment by melitele** [comment]
Thank you so much for the PR #14. The update is live now.
