### ISSUE TITLE
New "view-only" button not translated

### ISSUE THREAD

**Issue by syllant** [furkot/locale#11]
Tooltips are not translated for this button which is the most visible one in the toolbar (because underlined with an orange bar when activated).

I guess this is known, but more generally, should not you try to always add translations when you publish new labels? Either by requesting contribution from translators, or by using automated translation meanwhile?

**Comment by melitele** [comment]
I've updated the French .po file on the master branch marking all new translations as fuzzy. It'll be most appreciated if you can take a look. The interim fuzzy translations are deployed on the Furkot website as well.

We are still working on incorporating managing multiple language versions into our development and deployment process - hopefully we'll do better in time.

**Comment by syllant** [comment]
Done in https://github.com/furkot/locale/pull/12.

**Comment by pirxpilot** [comment]
Thanks! New version is deployed now.
