### ISSUE TITLE
"night" not translated for duration field in lodging stop

### ISSUE THREAD

**Issue by syllant** [furkot/locale#7]
Seen in French translation, e.g. "1 night" instead of "1 nuit".

**Comment by pirxpilot** [comment]
Good find. Need to add gettext annotations and deal with plurals there - or rework the form.

**Comment by melitele** [comment]
Places that display night/nights have been translated. I'll be most grateful if you can find time to review the updated French translation on the master branch.

**Comment by syllant** [comment]
Done in PR https://github.com/furkot/locale/pull/14.

**Comment by melitele** [comment]
Thank you so much. The update is live now.
