### ISSUE TITLE
Date picker not translated on first display

### ISSUE THREAD

**Issue by syllant** [furkot/locale#8]
Very minor issue: when you display the date picker for the first time, labels are not translated, e.g. you see the English month. As soon as you navigate across months, translation is applied and all is OK.

**Comment by pirxpilot** [comment]
Might be related to the fact that [code42day/calendar](https://github.com/code42day/calendar) is not yet properly localized...

**Comment by pirxpilot** [comment]
That should be fixed now - see: component/calendar#37
If you see that again, please re-open this issue.
